name: Deploy na VPS Integrator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: "https://agiazdqztkagivnenomq.supabase.co"
      VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnaWF6ZHF6dGthZ2l2bmVub21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MjI5MTAsImV4cCI6MjA4NjQ5ODkxMH0.E78QYVqCO4KC_QQVjpkfiMYWDTC63ss0QcKyF2IOfUo"
      VITE_SUPABASE_PROJECT_ID: "agiazdqztkagivnenomq"
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Deploy via SSH na VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/deploysites.online/"
          strip_components: 1
          rm: true

      - name: Reiniciar Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: sudo systemctl restart nginx
